# Generated by Django 3.0.6 on 2020-05-26 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200525_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='transastion_id',
            new_name='transaction_id',
        ),
    ]
